hik_camera_node:
  ros__parameters:
    device_index: 0
    publish_fps: 15.0
    frame_id: hik_camera_optical_frame
    image_topic: /hik_camera/image_raw
    force_mono8: false
    pixel_format: keep
    resize_scale: 1.0
    gain_auto: false
    gain: 23.0
svm_detector_node:
  ros__parameters:
    image_topic: /hik_camera/image_raw
    debug_topic: /vision/debug_image
    target_pose_topic: /vision/target_pose
    target_class_topic: /vision/target_class
    svm_model: /home/liar/UR7e/ros2_ws/src/ur7e_vision/config/svm_model.xml
    homography_file: /home/liar/UR7e/ros2_ws/src/ur7e_vision/calibration/homography.yaml
    labels_file: /home/liar/UR7e/ros2_ws/src/ur7e_vision/config/labels.yaml
    min_area: 500.0
    max_area: 10000000.0
    blur_size: 5
    threshold_mode: otsu
    binary_threshold: 100
    canny_low: 50
    canny_high: 150
    invert_binary: false
    target_z: 0.165
    target_frame: base
    fixed_qx: 0.9238700051322959
    fixed_qy: 0.38269617379663273
    fixed_qz: -0.0022329597426112052
    fixed_qw: 0.0016929468558880931
    use_detection_angle: true
    yaw_offset_deg: 0.0
    target_class_id: -1
    publish_when_no_svm: true
    stable_frames: 5
    stable_pixel_tolerance: 15.0 # 中心变动像素点的上限值
    use_detection_angle_for_bolt: true
    use_detection_angle_for_nut: true
    target_selection_mode: confidence
    min_target_score: 0.50
    target_match_radius_px: 150.0
    min_track_frames: 3
    min_class_consistency_frames: 3
    require_stable_position: true
    angle_vector_length_px: 100.0
